# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
- package-ecosystem: pip
  directories:
  - "_slides/*"
  schedule:
    interval: monthly
  labels:
  - python
  - dependencies
  - automerge
  allow:
  - dependency-name: "manim-slides"

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
  labels:
  - github-actions
  - dependencies
  - automerge

- package-ecosystem: bundler
  directory: /
  schedule:
    interval: monthly
  labels:
  - gems
  - dependencies
  - automerge
