[project]
name = "2023-07-17-siegen-presentation"
version = "0.1.0"
requires-python = ">=3.10,<3.12"
dependencies = [
    "manim-slides[manim]==4.14.0",
    "numpy>=1.26.4",
    "setuptools>=80.9.0,<81",
    "shapely>=2.1.1",
    "sympy>=1.14.0",
]
