[project]
name = "2024-03-18-eucap-presentation"
version = "0.1.0"
requires-python = ">=3.10,<3.12"
dependencies = [
    "manim-slides[manim]==5.5.2",
    "numpy>=2.2.6",
    "opencv-python>=4.11.0.86",
]

