name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'gh-pages'
          fetch-depth: 0
      - name: Merge main into gh-pages
        run: |
          #git checkout -b gh-pages
          #git branch --set-upstream-to gh-pages origin/gh-pages
          #git pull --all
          git reset --hard origin/main
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python dependencies
        run: |
          python -m pip install notebook
      - name: Convert notebooks to posts
        run: |
          [ -d _notebooks ] && [ "$(find _notebooks -type f -iname '*.ipynb')" ] && python -m jupyter nbconvert _notebooks/*.ipynb --to markdown --output-dir _posts/ || echo "No notebook found"
      - name: Push latest changes to gh-pages
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update gh-pages w/ respect to main'
          push_options: '--force'
          #branch: 'gh-pages'
