[project]
name = "2024-04-16-milan-presentation"
version = "0.1.0"
requires-python = ">=3.10,<3.12"
dependencies = [
    "av<14",
    "manim-slides[manim]==5.1.3",
    "numpy>=2.2.6",
    "opencv-python>=4.11.0.86",
]
