[project]
dependencies = [
  "manim-slides[manim]==5.5.1",
  "numpy>=2.2.2",
  "pillow>=11.1.0",
  "plotly>=5.24.1",
  "pyside6==6.6.1",
  "scipy>=1.15.1",
]
name = "2025-06-27-emts-presentation"
requires-python = ">=3.11"
version = "0.1.0"
